### ISSUE TITLE
Solution does not compile on VS2019

### ISSUE THREAD

**Issue by shaharprish** [GeirGrusom/IdGenerator#1]
When compiling on VS2019, I get the following error:

The project was cloned and executed as is. Are there any build instructions I need to follow?

1>------ Build started: Project: IdGenerator, Configuration: Debug Any CPU ------
1>IdGenerator -> C:\Users\User\Source\Repos\IdGenerator\src\IdGenerator\bin\Debug\netstandard2.0\IxSoftware.Generators.IdGenerator.dll
2>------ Build started: Project: IdGenerator.Tests, Configuration: Debug Any CPU ------
2>C:\Users\User\Source\Repos\IdGenerator\src\IdGenerator.Tests\GeneratedCodeTests.cs(19,50,19,73): error CS0535: 'DecimalTest' does not implement interface member 'IEquatable<DecimalTest>.Equals(DecimalTest)'
2>C:\Users\User\Source\Repos\IdGenerator\src\IdGenerator.Tests\GeneratedCodeTests.cs(9,46,9,65): error CS0535: 'IntTest' does not implement interface member 'IEquatable<IntTest>.Equals(IntTest)'
2>C:\Users\User\Source\Repos\IdGenerator\src\IdGenerator.Tests\GeneratedCodeTests.cs(14,47,14,67): error CS0535: 'GuidTest' does not implement interface member 'IEquatable<GuidTest>.Equals(GuidTest)'
2>Done building project "IdGenerator.Tests.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by GeirGrusom** [comment]
This requires Visual Studio 16.7 Preview to build, as code generation is part of that.

**Comment by GeirGrusom** [comment]
I've added a build error in the newest version if you try to build with a MSBuild version that doesn't support it.
